BulkyWeb/Areas/Admin/Controllers/CompanyController.cs
using Bulky.DataAccess.Repository.Interface;
using Bulky.Models.Models;
using Bulky.Models.ViewModels;
using Bulky.Utilities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding.Metadata;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BulkyWeb.Areas.Admin.Controllers
{
	[Area("Admin")]
	[Authorize(Roles = SD.Role_Admin)]
	public class CompanyController : Controller
	{
		private readonly IUnitOfWork _unitOfWork;
		
		public CompanyController(IUnitOfWork unitOfWork)
		{
			_unitOfWork = unitOfWork;			
		}

		public IActionResult Index()
		{
			List<Company> companyList = _unitOfWork.Company.GetAll().ToList();

			return View(companyList);
		}

		[HttpGet]
		public IActionResult Upsert(int? id)
		{
			if (id == null || id == 0)
			{
				// Create
				return View(new Company());
			}
			else
			{
				// Update
				Company companyObj = _unitOfWork.Company.Get(u => u.Id == id);
				return View(companyObj);
			}
		}

		[HttpPost]
		public IActionResult Upsert(Company companyObj)
		{
			if (ModelState.IsValid)
			{
				if (companyObj.Id == 0)
				{
					_unitOfWork.Company.Add(companyObj);
					_unitOfWork.Save();
					TempData["Success"] = "Company created successfully";
				}
				else
				{
					_unitOfWork.Company.Update(companyObj);
					_unitOfWork.Save();
					TempData["Success"] = "Company updated successfully";
				}
				return RedirectToAction("Index");
			}
			else
			{
				return View(companyObj);
			}
		}

		//public IActionResult Edit(int? id)
		//{
		//	if (id == null || id == 0)
		//	{
		//		return NotFound();
		//	}
		//	Company? productFromDb = _unitOfWork.Company.Get(e => e.Id == id);
		//	if (productFromDb == null)
		//	{
		//		return NotFound();
		//	}

		//	return View(productFromDb);
		//}

		//[HttpPost]
		//public IActionResult Edit(Company obj)
		//{
		//	if (ModelState.IsValid)
		//	{
		//		_unitOfWork.Company.Update(obj);
		//		_unitOfWork.Save();
		//		TempData["Success"] = "Company updated successfully";
		//		return RedirectToAction("Index");
		//	}
		//	return View();
		//}

		//public IActionResult Delete(int? id)
		//{
		//	if (id == null || id == 0)
		//	{
		//		return NotFound();
		//	}
		//	Company? productFromDb = _unitOfWork.Company.Get(e => e.Id == id);
		//	if (productFromDb == null)
		//	{
		//		return NotFound();
		//	}

		//	return View(productFromDb);
		//}

		//[HttpPost, ActionName("Delete")]
		//public IActionResult DeletePost(int? id)
		//{
		//	Company? obj = _unitOfWork.Company.Get(e => e.Id == id);
		//	if (obj == null)
		//	{
		//		return NotFound();
		//	}
		//	_unitOfWork.Company.Remove(obj);
		//	_unitOfWork.Save();
		//	TempData["Success"] = "Company deleted successfully";
		//	return RedirectToAction("Index");
		//}

		#region API CALLS
		[HttpGet]
		public IActionResult GetAll()
		{
			List<Company> companies = _unitOfWork.Company.GetAll().ToList();
			return Json(new { data = companies });
		}

		[HttpDelete]
		public IActionResult Delete(int? id)
		{
			var companyToBeDeleted = _unitOfWork.Company.Get(e => e.Id == id);
			if (companyToBeDeleted == null)
			{
				return Json(new { success = false, message = "Error while deleting" });
			}
			_unitOfWork.Company.Remove(companyToBeDeleted);
			_unitOfWork.Save();
			//TempData["Success"] = "Company deleted successfully";
			return Json(new { success = true, message = "Successfully deleted" });
		}
		#endregion
	}
}

BulkyWeb/Areas/Admin/Views/Company/Index.cshtml
<div class="card shadow border-0 my-4">
	<div class="card-header bg-secondary bg-gradient py-3">
		<div class="row">
			<div class="col-12 text-center">
				<h2 class="text-white py-2">Company List</h2>
			</div>
		</div>
	</div>
	<div class="card-body p-4">
		<div class="row mb-3">
			<div class="col-6"></div>
			<div class="col-6 text-end">
				<a asp-controller="Company" asp-action="Upsert" class="btn btn-primary">
					<i class="bi bi-plus-circle"></i> Create New Company
				</a>
			</div>
		</div>

		<table id="tblData" class="table table-bordered table-striped" style="width: 100%">
			<thead>
				<tr>
					<th class="text-center">Name</th>
					<th class="text-center">Address</th>
					<th class="text-center">Phone Number</th>
					<th class="text-center">City</th>
					<th class="text-center">State</th>
					<th class="text-center">Postal Code</th>
					<th class="text-center">Action</th>
				</tr>
			</thead>
		</table>
	</div>
</div>

@section Scripts
{
	<script src="~/js/company.js"></script>
}

BulkyWeb/Areas/Admin/Views/Company/Upsert.cshtml
@model Company

<div class="card shadow border-0 ms-0 my-4">
	<div class="card-header bg-secondary bg-gradient py-3">
		<div class="row">
			<div class="col-12 text-center">
				<h2 class="text-white py-2">@(Model.Id != 0 ? "Update" : "Create") Company</h2>
			</div>
		</div>
	</div>
	<div class="card-body p-4">
		<form method="post" enctype="multipart/form-data">
			<input asp-for="Id" hidden />			
			<div asp-validation-summary="ModelOnly" class="text-danger"></div>
			<div class="row">
				<div class="col-12">
					<div class="form-floating py-2 col-12">
						<input asp-for="Name" class="form-control border-0 shadow" />
						<label asp-for="Name" class="ms-2"></label>
						<span asp-validation-for="Name" class="text-danger"></span>
					</div>					
					<div class="form-floating py-2 col-12">
						<input asp-for="PhoneNumber" class="form-control border-0 shadow" />
						<label asp-for="PhoneNumber" class="ms-2"></label>
						<span asp-validation-for="PhoneNumber" class="text-danger"></span>
					</div>
					<div class="form-floating py-2 col-12">
						<input asp-for="StreetAddress" class="form-control border-0 shadow" />
						<label asp-for="StreetAddress" class="ms-2"></label>
						<span asp-validation-for="StreetAddress" class="text-danger"></span>
					</div>
					<div class="form-floating py-2 col-12">
						<input asp-for="City" class="form-control border-0 shadow" />
						<label asp-for="City" class="ms-2"></label>
						<span asp-validation-for="City" class="text-danger"></span>
					</div>
					<div class="form-floating py-2 col-12">
						<input asp-for="State" class="form-control border-0 shadow" />
						<label asp-for="State" class="ms-2"></label>
						<span asp-validation-for="State" class="text-danger"></span>
					</div>
					<div class="form-floating py-2 col-12">
						<input asp-for="PostalCode" class="form-control border-0 shadow" />
						<label asp-for="PostalCode" class="ms-2"></label>
						<span asp-validation-for="PostalCode" class="text-danger"></span>
					</div>					
					<div class="row pt-2">
						<div class="col-6 col-md-3">
							@if (Model.Id != 0)
							{
								<button type="submit" class="btn btn-primary form-control">Update</button>
							}
							else
							{
								<button type="submit" class="btn btn-primary form-control">Create</button>
							}
						</div>
						<div class="col-6 col-md-3">
							<a asp-controller="Product" asp-action="Index" class="btn btn-outline-primary border form-control">Back to List</a>
						</div>
					</div>
				</div>
			</div>
		</form>
	</div>
</div>

@section Scripts
{
	<script>
		tinymce.init
		({
		  selector: '#myTextarea', // Target the textarea by ID
		  height: 300,
		  menubar: false,
		  plugins: [
			  // Core editing features
			  'anchor', 'autolink', 'charmap', 'codesample', 'emoticons', 'link', 'lists', 'media', 'searchreplace', 'table',
			  'visualblocks', 'wordcount',
			  // Your account includes a free trial of TinyMCE premium features
			  // Try the most popular premium features until Nov 16, 2025:
			  'checklist', 'mediaembed', 'casechange', 'formatpainter', 'pageembed', 'a11ychecker', 'tinymcespellchecker', 'exportpdf',
			  'permanentpen', 'powerpaste', 'advtable', 'advcode', 'advtemplate', 'uploadcare', 'mentions', 'markdown',
			  'tableofcontents', 'footnotes', 'mergetags', 'autocorrect', 'typography', 'inlinecss', 'importword', 'exportword'
			],
		  toolbar: 'undo redo | blocks fontfamily fontsize | bold italic underline strikethrough | link media table mergetags |' +
				   'addcomment showcomments | spellcheckdialog a11ycheck typography uploadcare | align lineheight |' +
				   'checklist numlist bullist indent outdent | emoticons charmap | removeformat',
		});
	</script>
	@{
		<partial name="_ValidationScriptsPartial" />
	}
}